/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteBancoDados;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author vitor
 */
public class JFMenu extends javax.swing.JFrame {

    private String nomeUsuario;
    private String senhaUsuario;

    /**
     * Creates new form JFMenu
     */
    public JFMenu() {
        initComponents();
        
        URL url = this.getClass().getResource("/icone/logo1.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadUsuario = new javax.swing.JButton();
        btnCadVeiculo = new javax.swing.JButton();
        lblCadCarro = new javax.swing.JLabel();
        lbCadlUsuario = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        txtMenu = new javax.swing.JLabel();
        lblPesquisaUsu = new javax.swing.JLabel();
        btnConfUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 153));
        setResizable(false);

        btnCadUsuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnCadUsuario.setText("Cadastro de Usuario");
        btnCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUsuarioActionPerformed(evt);
            }
        });

        btnCadVeiculo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnCadVeiculo.setText("Cadastro de Veiculo");
        btnCadVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadVeiculoActionPerformed(evt);
            }
        });

        lblCadCarro.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblCadCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/car.png"))); // NOI18N

        lbCadlUsuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbCadlUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/usuario.png"))); // NOI18N

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        txtMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMenu.setText("Menu Principal");

        lblPesquisaUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/user.png"))); // NOI18N

        btnConfUsuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnConfUsuario.setText("Configurações de Usuario");
        btnConfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lbCadlUsuario)
                                .addGap(96, 96, 96)
                                .addComponent(lblPesquisaUsu))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnCadUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(btnConfUsuario)))
                        .addGap(27, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadVeiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCadCarro)
                                .addGap(36, 36, 36)))))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(txtMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCadlUsuario)
                    .addComponent(lblCadCarro)
                    .addComponent(lblPesquisaUsu))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadUsuario)
                    .addComponent(btnCadVeiculo)
                    .addComponent(btnConfUsuario))
                .addGap(18, 18, 18)
                .addComponent(btnVoltar)
                .addGap(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuarioActionPerformed
        // TODO add your handling code here:
        JFCadastroUsuario avancar = new JFCadastroUsuario();
        //Abrindo a janela principal
        avancar.setVisible(true);
        //Fechar a janela onde estou
        this.setVisible(false);

    }//GEN-LAST:event_btnCadUsuarioActionPerformed

    private void btnCadVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadVeiculoActionPerformed
        // TODO add your handling code here:
        JFCarro carro = new JFCarro();
        carro.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnCadVeiculoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        JFLogin login = new JFLogin();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnConfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfUsuarioActionPerformed
        // TODO add your handling code here:
        JFPermissao login = new JFPermissao();
        login.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_btnConfUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadUsuario;
    private javax.swing.JButton btnCadVeiculo;
    private javax.swing.JButton btnConfUsuario;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lbCadlUsuario;
    private javax.swing.JLabel lblCadCarro;
    private javax.swing.JLabel lblPesquisaUsu;
    private javax.swing.JLabel txtMenu;
    // End of variables declaration//GEN-END:variables
}
